---
imap_mailboxes:
  steve_main:
    server: imap.kolabnow.com
    port: 993
    username: steve@fryman.io
    password: bsKpcHdoYQTAmnozhABJWipLxDdmYULXg9stDhti4jPKZdvLih
    ssl: true
max_attachment_size: 1024
attachment_datastore_ttl: 1800

