---
name: Sample
description: "Rule which sends an email when an email from johndoe@gmail.com is received"
pack: email
enabled: false
trigger:
  type: email.imap.message
  parameters: {}
criteria:
  trigger.from:
    pattern: bravebautista96@gmail.com
    type: contains
action:
  ref: core.sendmail
  parameters:
    body: 'We received an email'
    to: bravebautista96@gmail.com
    from: rajshahu95@gmail.com
    subject: 'Email Received'
